### ISSUE TITLE
test.py found errors

### ISSUE THREAD

**Issue by megagosha** [marcbelmont/cnn-watermark-removal#21]
```
======================================================================`
ERROR: test_inference_voc (__main__.WatermarkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/watermark/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/watermark/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/ubuntu/anaconda3/envs/watermark/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key conv2d_9/kernel not found in checkpoint
	 [[Node: save_1/RestoreV2_117 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_117/tensor_names, `save_1/RestoreV2_117/shape_and_slices)]]
```

How to solve this error? Why is it happening? Thanks

**Comment by marcbelmont** [comment]
This project was developed using an old version of Tensorflow. See https://github.com/marcbelmont/cnn-watermark-removal/blob/master/requirements.txt to install the correct dependencies.
